/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lib.editor.widget.inspector;

import java.awt.Dimension;
import javax.swing.SpringLayout;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import lib.editor.data.game.DataBase;
import lib.editor.data.game.DataMap;
import lib.editor.mgr.WidgetMgr;
import org.jdesktop.swingx.JXTaskPane;
import org.jdesktop.swingx.JXTaskPaneContainer;

/**
 *
 * @author gaetan
 */
public class MapPanel extends InspectorPanel {

    
    /**
     * Creates new form PropertyPanel
     */
    public MapPanel(JXTaskPaneContainer container) {
        super(container, "Map", "project_root.png");
        
        initComponents();
        
        textPanel.setMaximumSize(new Dimension(LEFT_COLUMN_WIDTH, textPanel.getComponentCount()*28));
        textPanel.setPreferredSize(new Dimension(LEFT_COLUMN_WIDTH, textPanel.getComponentCount()*28));
    }

    public void refresh(DataBase data){
        DataMap dataMap = (DataMap) data;
        widthSpinner.setValue(dataMap.width);
        heightSpinner.setValue(dataMap.height);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        widthSpinner = new javax.swing.JSpinner();
        heightSpinner = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        textPanel.setMaximumSize(null);
        textPanel.setLayout(new java.awt.GridLayout(0, 1));

        jLabel2.setText("Width");
        jLabel2.setMaximumSize(new java.awt.Dimension(28, 28));
        jLabel2.setMinimumSize(new java.awt.Dimension(28, 28));
        jLabel2.setPreferredSize(new java.awt.Dimension(28, 28));
        textPanel.add(jLabel2);

        jLabel1.setText("Height");
        jLabel1.setMaximumSize(new java.awt.Dimension(28, 28));
        jLabel1.setMinimumSize(new java.awt.Dimension(28, 28));
        jLabel1.setPreferredSize(new java.awt.Dimension(28, 28));
        textPanel.add(jLabel1);

        jLabel3.setMaximumSize(new java.awt.Dimension(28, 28));
        jLabel3.setMinimumSize(new java.awt.Dimension(28, 28));
        jLabel3.setPreferredSize(new java.awt.Dimension(28, 28));
        textPanel.add(jLabel3);

        add(textPanel);

        jPanel2.setMaximumSize(null);
        jPanel2.setLayout(new java.awt.GridLayout(0, 1));
        jPanel2.add(widthSpinner);
        jPanel2.add(heightSpinner);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/refresh.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner heightSpinner;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel textPanel;
    private javax.swing.JSpinner widthSpinner;
    // End of variables declaration//GEN-END:variables
}
