/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lib.editor.ui;

import java.awt.Frame;
import javax.swing.JPanel;

/**
 *
 * @author gaetan
 */
public class ResourceManagerWindow extends Dialog {

    public ResourceManagerWindow(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        layoutDialog(0);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jSplitPane3 = new javax.swing.JSplitPane();
        jSplitPane4 = new javax.swing.JSplitPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mapTree = new lib.editor.widget.tree.tree.MapTree();
        jPanel5 = new javax.swing.JPanel();
        mapTreeFilterTextField = new lib.editor.widget.textfield.IconTextField();
        jPanel7 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXList1 = new org.jdesktop.swingx.JXList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Resource Manager");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.LINE_AXIS));

        jSplitPane4.setResizeWeight(1.0);

        jPanel6.setMinimumSize(new java.awt.Dimension(160, 226));
        jPanel6.setPreferredSize(new java.awt.Dimension(160, 226));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setAutoscrolls(true);

        mapTree.setAutoscrolls(true);
        mapTree.setDropMode(javax.swing.DropMode.ON_OR_INSERT);
        mapTree.setMaximumSize(null);
        mapTree.setMinimumSize(null);
        mapTree.setPreferredSize(null);
        mapTree.setRowHeight(18);
        jScrollPane2.setViewportView(mapTree);

        jPanel6.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        mapTreeFilterTextField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/find.png"))); // NOI18N
        mapTreeFilterTextField.setMaximumSize(new java.awt.Dimension(2147483647, 28));
        mapTreeFilterTextField.setMinimumSize(new java.awt.Dimension(20, 28));
        mapTreeFilterTextField.setPreferredSize(new java.awt.Dimension(24, 28));
        mapTreeFilterTextField.setStatusText("Live search filtering maps name.");
        jPanel5.add(mapTreeFilterTextField);

        jPanel6.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jSplitPane4.setLeftComponent(jPanel6);

        jButton3.setText("jButton3");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(125, 125, 125))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(123, 123, 123))
        );

        jSplitPane4.setRightComponent(jPanel7);

        jSplitPane3.setRightComponent(jSplitPane4);

        jPanel4.setMinimumSize(new java.awt.Dimension(160, 226));
        jPanel4.setPreferredSize(new java.awt.Dimension(160, 226));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jXList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jXList1);

        jPanel4.add(jScrollPane1);

        jSplitPane3.setLeftComponent(jPanel4);

        mainPanel.add(jSplitPane3);

        getContentPane().add(mainPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JSplitPane jSplitPane4;
    private org.jdesktop.swingx.JXList jXList1;
    private javax.swing.JPanel mainPanel;
    private lib.editor.widget.tree.tree.MapTree mapTree;
    private lib.editor.widget.textfield.IconTextField mapTreeFilterTextField;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean ok() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean cancel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void refresh() {
    }

    @Override
    public JPanel getMainPanel() {
        return mainPanel;
    }
}
